namespace: my-app-cluster-stage

resources:
  - ../base
  - namespace.yaml 
  
patches:
- path: cluster-claim.yaml 
  target:
    group: kubernetes.example.com
    version: v1alpha1
    kind: AksClusterClaim
    name: my-app-cluster
- patch: |-
    - op: replace
      path: /metadata/name
      value: my-app-cluster-stage  
  target:
    kind: AksClusterClaim   